config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :students
  resources :courses
  resources :sections
  resources :semesters
  resources :prefixes

  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root:to => 'home#index'
end

app/views/prefixes/_form.html.erb
<%= form_with(model: prefix) do |form| %>
  <% if prefix.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prefix.errors.count, "error") %> prohibited this prefix from being saved:</h2>

      <ul>
        <% prefix.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :prefix, style: "display: block" %>
    <%= form.text_field :prefix %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prefixes/_prefix.html.erb
<br />
<div id="<%= dom_id prefix %>">
  <p>
  <br /><strong>Prefix:</strong>
    <%= prefix.prefix %>
  </p>

</div>

app/views/prefixes/index.html.erb
<%= form_with url: prefixes_url, method: :get, data: { turbo_frame: "results", turbo_action: "advance"} do |form| %>

  Prefix Search <%= form.search_field :query, value: params[:query], onsubmit: "this.form.requestSubmit()" %>

<% end %>

<%= turbo_frame_tag "results" do %>

  <div id="prefix">

    <% @prefixes.each do |prefix| %>

      <%= render prefix %>

      <p>

      <b> <%= link_to "Show this prefix", prefix %> </b>

      </p>

    <% end %>

  </div>

<% end %>

<b> <%= link_to "New prefix", new_prefix_path %> </b>

app/views/prefixes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prefix %>

<div>
  <%= link_to "Edit this prefix", edit_prefix_path(@prefix) %> |
  <%= link_to "Back to prefixes", prefixes_path %>

  <%= button_to "Destroy this prefix", @prefix, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :IDnumber, style: "display: block" %>
    <%= form.number_field :IDnumber %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<br />




<div id="<%= dom_id student %>">
  <p>
  <br /> <strong>Name:</strong> 
    <%= student.name %>
 
    <br /><strong>Idnumber:</strong> 
    <%= student.IDnumber %>

    <br /> <strong>Email:</strong> 
    <%= student.email %>

    <br /><strong>Phone:</strong> 
    <%= student.phone %>

    <br /><strong>Address:</strong> 
    <%= student.address %> 

  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>



<%= form_with url: students_url, method: :get, data: { turbo_frame: "results", turbo_action: "advance"} do |form| %>

  Search Student Name <%= form.search_field :query, value: params[:query], onsubmit: "this.form.requestSubmit()" %>

  

<% end %>

<%= turbo_frame_tag "results" do %>

  <div id="students">

    <% @students.each do |student| %>

      <%= render student %>

      <p>

      <b><%= link_to  "Show this student", student %></b>

      </p>

    <% end %>

  </div>

<% end %>

<b><%= link_to "New student", new_student_path %></b>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>